# Generated by Django 2.0 on 2017-12-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingimages',
            name='date_build_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
