# Generated by Django 2.0 on 2017-12-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20171218_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingimages',
            name='date_build_year',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
