# Generated by Django 2.1.7 on 2019-06-26 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('galleries', '0006_auto_20190625_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingimages',
            name='description',
        ),
        migrations.RemoveField(
            model_name='buildingimages',
            name='thumb_image',
        ),
    ]
