# Generated by Django 2.1.7 on 2019-06-27 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('galleries', '0008_auto_20190626_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingimages',
            name='imgorigsize',
        ),
    ]
