# Generated by Django 2.1.7 on 2019-06-29 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('galleries', '0010_auto_20190629_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
