# Generated by Django 2.1.7 on 2019-07-08 10:08

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galleries', '0012_auto_20190706_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000)),
                ('title', models.CharField(max_length=64)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='images',
        ),
        migrations.RemoveField(
            model_name='category',
            name='location',
        ),
        migrations.RemoveField(
            model_name='buildingimages',
            name='title',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(to='galleries.BuildingImages'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Location'),
        ),
        migrations.AddField(
            model_name='project',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='galleries.LogHomeModel'),
        ),
    ]
