# Generated by Django 2.1.7 on 2019-07-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galleries', '0013_auto_20190708_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loghomemodel',
            name='bathroom',
            field=models.FloatField(default=1),
        ),
    ]
