# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 18:03
from __future__ import unicode_literals

import article.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletext',
            options={'ordering': ['-created_date'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='articletext',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, size=[1280, 720], upload_to=article.models.static_folder),
        ),
    ]
