# Generated by Django 2.0 on 2017-12-20 17:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171207_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletext',
            name='article_text',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
